# Site settings
title: 
header-img: img/home-bg.png
email: tylermaxwell661@gmail.com
copyright_name: tmax818
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: tmax818
github_username:  tmax818
learn_profile: tmax818
email_username: tylermaxwell661@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
