* Chemistry


** Unit 1 - Properties of Matter

*** Assessment 1.1 - Observing Matter:

In this assessment students observed three disc magnets suspended on a rod. The idea was to get them to think about forces on matter that would be
discussed in the unit lessons. This worked moderately well, although the concept of forces with a direction was difficult for many.


*** Lesson 1.1 - Composition of Matter:

Atomic and molecular structure of matter and units of mass and length.


*** Lesson 1.2 - Volume, Mass, and Density:

Definition of density and relationship to sinking and floating; practice calculating density.


*** Lesson 1.3 - Forces on Matter:

Properties of gravitational and electromagnetic forces.


*** Assessment 1.2 - Explaining Forces on Matter:

Students did this assessment after learning about the source and nature of gravitational and electromagnetic forces. It was a good test of their ability to recognize these forces in a simple situation and to explain what they observed.


*** Lesson 1.4 - Temperature and Matter:

Definition and units of temperature; uses a very goodPhet simulation relating temperature to molecular motion. I referred back to this
simulation many times during the year.


*** Lesson 1.5 - States of Matter:

Relationship between the three states of matter and intermolecular forces; definition of phase changes; definition of a physical change


*** Lesson 1.6 - Solar Distillation:

Phase changes in the hydrologic cycle; how a solar still works. This lesson included the construction of a solar still for each period using
materials that are in the Room 306 back area. The students enjoyed this activity. I took
the still home and reported back on its performance. The previous year each table group
made a still and we put them out on the roof of the building, but this year they would not
let us go on the roof.


*** Assessment 1.3 - A Water Plan for Your Home and Community:

This assessment was directly related to the lesson on solar stills and was an attempt to get the students to apply this
information qualitatively and quantitatively to their home and community within a scenario of
scarce fresh water.



** Unit 2 - Combustion

*** Assessment 2.1 - Observing Combustion:

Students observe and reflect on a burning candle. This assessment continues the theme for the first assessment in which they are asked to
describe what they see and also speculate about what they cannot see. One possible extension
of this in the amazing parte would be to ask them to formulate a question about what they see
that involves what they cannot see.

****  Lesson 2.1 - Computing the Energy in Food

- The modern metric unit of energy is the **joule**. 
- An older unit of energy is the **calorie**.
- To convert use: **1 calorie = 4.2 joules**
- A food calorie = 1000 energy calories = 1 kilocalorie = 1 kcal

***** Food Label Exercise

1. Get a food label by Googling “food label images”.
2. Find the grams per serving (if your label does not have this, get another one that does).
3. Find the food calories per serving on the label - remember that these are actually kcal of energy.
4. Compute the kcal per gram:
	Calories per serving = _________________________________
	Grams per serving = ___________________________________
	
5. Post your kcal/gm value on a sticky note on the number line on the white board. 
6. Class value = ________________________ cal/g

Example Calculation

Calories per serving = 300 food calories = 300 kcal
Grams per serving = 102 g = 2.9 kcal/g


*** Lesson 2.1 - Computing the Energy in Food:

Units of energy; computing the energy per
mass in food using food labels; displaying the results as a histogram of sticky notes on a
number line on the back white board.


*** Lesson 2.2 - Biofuels Lab:

Lab materials and procedure copied from a PowerPoint to a
single sheet in their notebook; data on water volume and temperature and nut mass.
Reflection on kinds and sources of error.


*** Assessment 2.2 - Calculating the Energy Increase in Water:

This assessment uses the data from the biofuel lab and asks students to calculate the energy increase in their mass of water
using the specific heat of water and the measured temperature increase. Students then
calculate the energy going into the water per mass of nut burned and compared it to the energy
per mass of food measured in Lesson 2.1. Students were asked to defend a claim about
whether all the energy from the nut went into the water. This was a difficult assessment for
many students, even though an example calculation was provided. They are very challenged by
math calculations. They were also challenged by having to use concepts such as less than or
greater than in making their claim.


*** Lesson 2.3 - Combustion Conference:

Individual, group, and class responses to three questions about the combustion lab. I did this using a Fishbowl routine in which
representatives from each table came to a central table to discuss the questions. I used
the sentence starter sheets to guide the discussion. I provided the wording for the class
response.


*** Lesson 2.4 - Combustion Video Questions:

Students watched a video about combustion and filled in words from a word bank into statements taken from the video.


*** Assessment 2.3 - Real World Combustion Project:

Each student chooses a fuel and does research on the properties of the fuel. I would say that the Amazing question about the
relevance of the fuel to home, community, culture, or country needs to be more well-defined and
a bit more demanding. As it is, students dash off a couple of sentences.


** Unit 3 - Energy 

Note this is a large unit with several distinct parts, including heat transfer, plate tectonics, and energy systems

*** Assessment 3.1 - Observing Lava Flowing into the Ocean:

Students watch a video of lava flowing into the ocean and respond with their observations of what they can and cannot see.


*** Lesson 3.1 - Hot Rocks Minilab:

In this lab students observe cold water being poured
over heated marbles (>200C) and to measure the temperature of the marbles and water
before and after they are combined. We use the IR thermometer that is in one of the
lower supply drawers in the front table. The dishes and marbles are in the cabinets in the
storeroom across the hall. I bought a toaster oven from home to heat the marbles.


*** Lesson 3.2 - Hot Rocks Discussion:

We did this using the Fishbowl routine with sentence starters.


*** Lesson 3.3 - Heat Transfer Lab:

Students heat up water using radiation, conduction, and
convection. As part of the data analysis they calculate how much energy was transferred
to the water.


*** Lesson 3.4 - Heat Transfer Reflection:

After the students try to answer the question about how heat was transferred for each case I use red plastic chips to illustrate how the
transfer takes place. Then I show them the class answer for them to copy. This is not a
perfect way for them to learn how each kind of heat transfer works, but it seems to get
the point across. A possible tweak would be to make the names of the three modes of
heat transfer more prominent given how much we are going to refer to them.


*** Lesson 3.5 - Heat Transfer Conference:

After students try to draw their individual responses each table uses a felt board and felt elements to draw what they think the
answer is. This exercise is difficult because all of a sudden we are talking about more
than one mode of transfer happening for each case. I walk around helping the tables
make their diagrams and then each table shares its diagram. Finally, I project the class
answer for them to copy.


*** Lesson 3.6 - Heat Transfer Video:

This is a somewhat creepy but effective video for
helping them remember the essential elements of each mode of transfer.


*** Lesson 3.7 - Plate Tectonics Video:

This video is a good introduction to plate tectonics.


*** Lesson 3.8 - Convection Remembrance, Minilab, Video, and Reflection:

The remembrance is what happened in the heat transfer lab with convection. The Minilab is a
pyrex baking pan on a hot plate with a light above and potassium permanganate crystals
dropped in to show the convection pattern after about 5 minutes of heating. I used to let
the students do the lab, but this year I just demonstrated it at the front table using the
data camera. The movie is part of the plate tectonics video. The reflection should
comment on how each part of the lesson shows heated material rising upward carrying
energy.


*** Lesson 3.9 - Dynamic Earth Reading:

The lesson has a pre-read part involving vocabulary and statements about plate tectonics the student agree or disagree with.
Then they do the reading and provide responses to selected sentences. The last thing
they are supposed to do is go back to the statements and correct any agreement or
disagreement that is wrong and for those statements that are wrong they should write
what is correct. For some reason students find it hard to understand what to do in this
last part.


*** Assessment 3.2 - Plate Tectonics:

For the Must Have they make and annotate a drawing showing the basic parts of the Earth’s interior and how heat is moved. For the Amazing they
should say how plate tectonics has affected life on Earth.


*** Lesson 3.10 - Forms of Energy:

This is the beginning of the last part of the energy unit. Six kinds of energy are identified - three are forms of kinetic energy and three are forms
of potential energy. The scenarios have been a good way to lock in their understanding.


*** Lesson 3.11 - Energy Systems:

This is the only place that conservation of energy is
discussed. The Phet app is excellent for visualizing energy systems.


*** Lesson 3.12 - Energy System Minilab:

This is a fun hands-on activity that uses different
material. Teapots on a hotplate; large lights as radiation source; batteries; solar panels;
propellers; spools; generator/motors that the spools and propellers go on; small lights;
LED lights, pulleys, weights, frictionless cars. Students construct enough energy
systems, usually three but sometimes two, that have all six kinds of energy.


*** Assessment 3.3 - Energy Systems Project:

This project asks students to conceive of a realworld energy system and to answer questions about their system.
Energy Reflection: This is a fun way to end the semester by completing an artistic work
(drawing, clay sculpture, poem, etc.) that expresses how the student thinks about energy. Clay
has been the most popular media, so if you do this you should buy a lot of clay from Amazon or
Staples. This is what I bought:
You can see the results of the last two years of this reflection at
https://docs.google.com/presentation/d/1B5buiE6xG3_QRVsaKglTQBbGpzm4ieviKveCKPNN1c/edit?usp=sharing and
https://docs.google.com/presentation/d/1ancEMCWdatOIscAvzfdXsEPLHiFmw5pq5_drTLmFd8k/edit?usp=sharing.


** Unit 4 - Atoms and Elements

*** Assessment 4.1 - Mystery Tubes:

This assessment introduces the idea of trying to figure out
what is inside something when you cannot see what is inside. The mystery tubes and the
materials for making model tubes are in the storeroom across the hall.


*** Lesson 4.1 - Atomic Model Research:

Each student is assigned one of the five atomic
models and does research on that model using the graphic organizer. Students at the
same table have different assignments. Then students meet in groups by the model they
were assigned and make a slide presentation and a poster.


*** Lesson 4.2 - Atomic Model Timeline:

Students take notes on the presentations of each model, noting the claims made by each model.


*** Lesson 4.3 - Element Property Lab:

Students make measurements on seven different element samples.


*** Lesson 4.4 

Students practice categorizing different objects and then try to categorize
the element samples.


*** Lesson 4.5 - Periodic Table Notes:

Introduces the essential features of the periodic table.


*** Lesson 4.6 - Periodic Table Practice:

Students practice identifying the properties of elements using the periodic table notation.


*** Assessment 4.2 - Build an Atom:

Students us a Phet app to practice building atoms with specific properties and identifying element isotopes.


*** Lesson 4.7 - Bohr Electron Diagram Notes:

Introduces the properties of a Bohr atom and how it is represented in an electron diagram.


*** Lesson 4.8 - Drawing Bohr Electron Diagrams:

Students practice drawing the diagrams for elements 1 through 18. This is a super important lesson because we refer to it a lot in
future lessons.


*** Lesson 4.9 - Electronegativity:

Students add electronegativity values to the Lesson 4.8 diagrams and then discuss the trends in electronegativity values.
Assessment 4.3 - Adopt an Atom: Each student is assigned a different element and does research to identify the properties of that element.


** Unit 5 - Bonding and Material Properties

*** Assessment 5.1 - Observing a Paper Towel and Water:

Students observe paper towel lifting water from one cup to another.


*** Lesson 5.1 - Properties of Water Lab:

This is a fun, but logistical, lesson where students observe water flowing down a cord, sticking to a penny, mixing with oil and alcohol, and
dissolving salt.


*** Lesson 5.2 - Properties of Water Lab Discussion:

After the concepts of cohesion and adhesion are introduced students try to explain what they saw in the lab.


*** Lesson 5.3 - Lewis Dot Diagrams and Ion Formation:

Student learn about these two concepts.


*** Lesson 5.4 - Practice forming Ions:

Students use the notation to show how anions and cations are formed.


*** Lesson 5.5 - Bonding Between Atoms:

Introduces the concept of “happy” atoms with full shells. Uses the excellent Happy Atoms that are in the back 306 room in conjunction with
a bonding game.


*** Assessment 5.2 - Adopt a Molecule:

Each student is assigned a different molecule and does research to identify the properties of that molecule.


*** Lesson 5.6 - Making New Material Lab:

Students combine calcium chloride and sodium alginate to form solid alginate material and then show that sodium chloride will not do the same thing. There is alginate solution in the refrigerator.


*** Lesson 5.7 - Making New Materials Discussion:

Students use felt boards to discuss why calcium chloride sticks the alginate together.


*** Lesson 5.8 - Polar and Non-Polar Bonds:

Introduces polarity and relates it to material properties


*** Lesson 5.9 - Intermolecular Force Practice:

A worksheet to help students understand the importance of intermolecular forces.


*** Assessment 5.3 - Adopt a Material:

Each student is assigned a different matieral and does research to identify the properties of that material.


** Unit 6 - Chemical Reactions

*** Assessment 6.1 - Observing a Reaction:

Students observe baking soda and vinegar reacting.


*** Lesson 6.1 - Reaction Mass Conservation Lab:

Students measure the mass of solids and
liquids before and after a reaction.


*** Lesson 6.2 - Reaction Mass Conservation with Happy Atoms:

Students use the Happy
Atoms to show that the number of atoms of each element in a reaction is conserved.


*** Lesson 6.3 - Mass Conservation in Reactions:

Students learn about molecular notation
and how to use that to determine the number of molecules of reactants and products.
Note: students are not retaining what the notation 2H2O means in terms of the
number of each atom and also they are not retaining the idea that H2O represents a
molecule. Anything that can be done to solidify this idea for them will help in the
next lessons.


*** Lesson 6.4 - Reaction Mass Conservation Computations:

Students learn how to compute the mass of reactants and products. Note: I do not use moles at all in my lessons.
The word “mole” appears only once in the Three Course Model writeup for
Chemistry.


*** Lesson 6.5 - Reaction Mass Conservation Practice:

More practice showing that total mass is conserved.


*** Assessment 6.2 - Reaction Mass Conservation:

Student are assigned one of four reactions for which they show that total mass is conserved.


*** Lesson 6.6 - Battery Minilab:

Students make batteries out of potatoes or lemons (about 30 of each is enough - they can be reused) and measure the voltage and show that by
adding elements in series the voltage goes up enough to lite a small LED.


*** Lesson 6.7 - The Lemon and Potato Battery Explained:

Students watch a video about the invention of the battery and then take notes on how it works. Note: in my notes the
electrons end up reacting with hydrogen ions; some sources have the electrons
combining with copper ions in solution to reform solid copper.


*** Lesson 6.8 - Reactions and Energy:

The Happy Atoms are used in conjunction with notes to show that in a reaction energy is first added to break up the reactants and then
emitted when the products are formed. The concept of exothermic and endothermic
reactions is introduced.


*** Lesson 6.9 - Ocean Acidification Minilab:

This lab uses a Phet app to define pH.
Students show that vinegar is acidic and will dissolve shells. Students show that adding CO2 to water makes it more acidic.


*** Assessment 6.3 - Adopt a Reaction:

Each student is assigned a different reaction and does research to identify the properties of that reaction


*** Lesson 6.10 - Ocean Acidification Video:

Provides more information about ocean acidification.



** Unit 7 - Climate Change

*** Assessment 7.1 - Climate Change Reflection:

Students interpret what four graphs show in terms of climate change.

*** Lesson 7.1 - Climate Change Videos:

Students watch videos on each of the four climate change topics.

*** Assessment 7.2 - Climate Change Miniquizes:

Students use material provided to pass a miniquiz on each of the four climate change topics.

*** Lesson 7.2 - Climate Change Simulations:

Students us a simulation app to show how
different emission scenarios affect the severity of climate change.

*** Assessment 7.3 - Climate Change Research:

Students define a climate change research
question and do research to answer it.



* Physics

Note: Most physics courses start with motion and then move on to unbalanced forces
that cause the motion. I reverse this and start with forces because in the real world most
things do not have unbalanced forces.




** Unit 1 - Forces

*** Assessment 1.1 - Observing a Car on a Hill:

Students view a video of cars trying to drive up a
hill, some making it and some not.

*** Lesson 1.1 - Experiencing Forces:

Students go to stations and experience forces by
gravity, friction, springs, and moving air.

*** Lesson 1.2 - How do Forces Act On an Object:

This lesson defines body, normal, and
tangential forces and shows how to draw them.

*** Lesson 1.3 - Forces Between Objects:

Students go to stations and experience different
examples of forces between two objects with the intention of learning Newton’s Third Law
about equal and opposite forces.

*** Lesson 1.4 - Free Body Diagrams:

Students learn how to draw free body diagrams.

*** Lesson 1.5 - Practice Drawing Free Body Diagrams

*** Assessment 1.2 - Real World Force Analysis:

Students define a situation with the three kinds of
forces present and draw a free body diagram for the situation.

*** Lesson 1.6 - Force Lab:

Students go to stations to measure gravitational force vs. mass,
static friction force vs. normal force, spring force vs. spring extension, and string forces
vs. pulling force

*** Lesson 1.7 - Force Conference:

Students analyze the data from the force lab to derive
linear equations that predict the force for each station.

*** Lesson 1.8 - Force Models and Practice:

Conventional equations for gravitational force,
static friction force, and spring force are defined. Students practice using these
equations.

*** Lesson 1.9 - Force Direction Minilab:

Students measure the tangential force needed to
hold a car on a slope as a function of the steepness of the slope.

*** Lesson 1.10 - Forces as Vectors:

Students learn about the vector nature of forces and
how to represent force components using trigonometric functions.

*** Assessment 1.3 - Forces on a Car on a Hill:

Students use what they have learned about forces
to calculate the gravitational, normal, and tangential forces on a car on a hill.


** Unit 2 - Forces and Motion

*** Assessment 2.1 - Observing a Collision:

Students watch a video of a car crashing into a wall
and record their observations.

*** Lesson 2.1 - Computing the Sum of Forces on an Object:

Students learn how to compute
the net force on an object.

*** Lesson 2.2 - Newton’s First Law:

Students us a Phet app to find that only when the sum
of forces is not zero will the state of motion of an object change.

*** Lesson 2.3 - One-dimensional Distance and Displacement:

Students learn the definitions
of distance and displacement and practice by doing their own walks.

*** Lesson 2.4 - 2D Distance and Displacement:

Students do a graphical exercise in
computing 2D distance and displacement.

*** Lesson 2.5 - Definition and Measurement of Velocity:

Students discuss the definition of
velocity and use the constant velocity cars to practice measuring velocity.

*** Assessment 2.2 - Observe the Motion of an Object: Students observe the motion of an object at
home and compute its velocity.

*** Lesson 2.6 - Velocity Notes and Practice:

Students learn the equations for computing
velocity and solve practice problems. I always do this with table groups using the large
white boards.

*** Lesson 2.7 - Acceleration Notes:

Students learn the definition of and equations for
computing acceleration and solve practice problems.

*** Lesson 2.8 - Kinematic Equations:

Students are shown the derivation of the kinematic
equations and solve practice problems. Note: it is clumsy to derive these equations
without calculus. There are several ways to do it and this way seems the most
intuitive, although I think few students really bother to understand the derivation.
The requirement for constant acceleration should be stressed.

*** Lesson 2.9 - Force, Mass, and Acceleration Lab:

Students measure the time it takes a
mass to go a given distance pulled by a known force. They discuss the results to derive
Newton’s Second Law F = ma. Note: this is a great lab requiring them to pay
attention to the setup. It can be sensitive to the table being not level and to friction
on the string, but over several years it has given pretty accurate results when all
the table group results are averaged (spreadsheet is in the Teaching Folders).

*** Lesson 2.10 - Newton’s Court:

Students work in groups to check if a statement about
force, mass, and acceleration are correct. Note: after lesson 2.9 I gave each student
a diploma of graduation from Newton’s Law School. The Mail Merge spreadsheet
is in Dropbox.

*** Lesson 2.11 - Observations of Collisions:

Students use the frictionless cars in either
sticky (velcro) or bouncy (magnets repelling) mode to make observations of velocity of
each car after a 1D collision.

*** Lesson 2.12 - Momentum Notes and Calculations:

Students learn the definition of
momentum and impulse and the application of momentum conservation to a collision.
They complete practice problems.

*** Lesson 2.13: Momentum Minilab:

Students use the frictionless cars and velocity gates to
verify if momentum is conserved in a collision.

*** Assessment 2.3 - Analysis of a Collision:

Each student at a table is assigned a different video of
cars crashing that includes a slow motion version, the mass of the car, and the value of the
approach velocity. Students analyze the videos to compute stopping times and then compute
the stopping acceleration and distance and the force of the collision. They then calculate the
necessary stopping time and distance to prevent damage to occupants of the cars. Note: by 
this time I have introduced the students to the idea that any acceleration more than about
10 m/sec2 is damaging.

Egg Drop Activity: In the first week of the Winter semester the students work in table groups
to make either an egg catcher or an egg protector. The designs are tested by dropping them
from the third floor balcony. Students complete a reflection about this activity.


** Unit 3 - Gravity and Motion

*** Assessment 3.1 - Observing a Ball:

Students watch a ball being thrown upward from a moving
car. This is a good video, but the assessment needs editing to direct the students to the parts
that are different.

*** Lesson 3.1 - Tossing a Bean Bag:

Students take notes on the application of the kinematic
equations to vertical motion and then after tossing a bean bag into the air and observing
how high it goes they practice calculating the initial velocity, the rise time, the fall time
and the final velocity. This is a very dense lesson that could be split into two.

*** Lesson 3.2 – Particle Trajectory Lab:

Students use the projectile launchers to find the
initial angle that makes the distance to impact the greatest. This is a good exercise in
group measurement.

*** Lesson 3.3 - Projectile Trajectory Exercise:

Students use the kinematic equations to
calculate characteristics of a projectile launch and to compare their results with a Phet
simulation.

*** Assessment 3.2 - Explaining a Ball:

Students use projectile theory concepts expressed in words
not equations to explain why the ball in Assessment 3.1 fell back into the truck and why two of
the tests are different (air resistance). Make sure the assessment refers to the correct tests in
the videos.

*** Lesson 3.4 – Investigating Gravity:

Students learn about the master equation for gravity
using Phet simulation and making calculations.

*** Lesson 3.5 – Investigating Centripetal Acceleration:

Students learn the theory of
centripetal acceleration and use the theory to make calculations.

*** Lesson 3.6 – Centripetal Force Lab:

Students use experimental equipment to measure
the centripetal acceleration. This is another good exercise in group measurement, but it
turns out to be hard to do correctly, and there is likely a large error resulting from friction
between the string and the tube. See the spreadsheet with class data in the 2023-24
Teaching Folders.

*** Lesson 3.7 – Gravity and Planets:

Students learn about how gravity affects the force on
objects at the surface of a planet, the orbital period of the planet, the planet escape
velocity, and which gases a planet will retain in its atmosphere.

*** Assessment 3.3 – Design Your Own Planet:

Students use the theory in Lesson 3.7 to propose a
new planet and to calculate characteristics of the planet. Note: this assessment uses the
Planetary Calculator in the 2023-24 Teaching Folders. The equations used here come from a
source I researched. Contact me for more details. I think the questions on this assessment
could be improved to require that the planet be habitable by humans.


** Unit 4 – Electromagnetism

*** Assessment 4.3 – Observing a Balloon:

Students observe a balloon and a sweater in a Phet
simulation and record their observations.

*** Lesson 4.1 – The Triboelectric Effect:

This lesson is intended to demonstrate static
electricity forces between different materials, but it never works consistently so I would
abandon it. An alternate lesson that might be interesting would be to use a balloon and a
PVC rod to measure the force on the balloon by observing the angle of deflection (this
would require they remember how to use trigonometry to compute forces).

*** Lesson 4.2 – Electrostatic Force:

Students take notes to learn about electrostatic charge
and forces.

*** Lesson 4.3 – Coulomb’s Law Calculations:

Students use a Phet simulation to make
calculations of electrostatic force. Note there does not seem to be any way to do this
experimentally in a quantitative way.

*** Lesson 4.4 – Magnetic Field Notes:

Students take notes on magnetic fields.

*** Assessment 4.2 – Magnetic Field Measurements:

Students use compasses to trace the
magnetic field of a bar magnet and also to answer questions qualitatively about disc magnets.
Note – the compasses and magnets are in drawers 7 and 8 in Room 302. The bar magnets are
marked on one side make it easier to keep track of north and south, but the marks may have
rubbed off.

*** Lesson 4.5 – Magnetic Fields and Moving Charges:

Students learn the theory of electromagnets and make a simple electromagnet from a nail and wire. Note: the nails
and wire and batteries and little metal pieces to attract are in drawers 9 and 11 in Room
302.

*** Lesson 4.6 – Right Hand Rule Practice:

Students learn about the Lorentz force and make a small reminder out of tape and a pipecleaner (in drawer 16 in Room 302).

*** Lesson 4.7 – Rail Guns:

Students work in groups to make rail guns. Supplies are in
drawers 9 and 11 in Room 302. Note that it is important that the aluminum foil be really
smooth and that the rail gun base and attaching wires be taped down to the table. See
below and note that it works better if you use two magnets stacked up.

*** Lesson 4.8 – Building an Electric Motor:

Students work in teams to build an electric motor. The rotor coil is made by wrapping wire around a glue stick. There are plyers in
the bottom large drawer in the front desk and paper clips in the top large drawer. The
paperclips and wires should be firmly taped to the table. The arms of the rotors need to
be sanded to promote contact with the paperclips. Magnets wires and batteries are in the
drawers in Room 302. Note: these disc magnets are VERY difficult to handle. If they are
stuck together they are hard to get apart. If they are apart and get close they will jump
together forcefully and can draw blood! I think they are stored in groups of two or three. I
always taped these in groups of two or three (however they are stored) onto a side table 
and moved them myself with the tape when the students had everything else ready.
Note also that for the motor to work the rotor arms need to be as straight as possible and
the rotor has to be as symmetrical as possible. The motor is started by spinning the
rotor.

*** Assessment 4.3 – Electromagnetic Force Design:

Students will propose a way to use an electromagnetic force to move a mass, and for maximum credit will compute the force needed
and the electrical and magnetic quantities necessary to move the mass. A summary sheet
about electromagnetic forces is provided. This assessment only worked partially well. Students
had trouble conceptualizing the problem, remembering how to compute the force to make a
mass move, and in addition it was difficult for them to come up with the electrical and magnetic
quantities.


** Unit 5 – Waves

*** Assessment 5.1 – Observing Waves:

Students make waves using a variety of equipment and
record their observations. The wave stations are:
• Ropes and phone cords – in Room 302.
• Slinkys – in Room 302 cabinet to the right – watch these closely – last year a student
stole one.
• Waves on a desktop – I used an iPad set to a seismometer app. Students hit the desk to
make the needle move.
• Waves in a water channel – I tool this home – sorry!
• Waves in a water dish – I suspended a pyrex baking dish containing about a half inch of
water between two ring stands using clamps and also a light above the dish on a ring
stand. Students used a pipette to drop water in the dish and observe the shadow of the
waves on a white piece of paper below the dish.
• Sound waves in air. In Room 302 in a low cabinet to the left there are instruments.
This assessment is super non-challenging – perhaps a harder Amazing question could be
posed.

*** Lesson 5.1 – Brainstorming Waves:

Students worked in groups to answer four questions
about waves on large poster paper (in Room 306 back room).

*** Lesson 5.2 – Observing Waves on a String:

Students use a Phet simulation to observe
waves on a string and come up with the important observable characteristics of waves.
At the end of the lesson I helped them identify these charqcteristics:
• Wave shape
• Wave speed
• Wave length
• Wave amplitude or height
• Wave period and frequency

*** Lesson 5.3 – Measuring Waves on a String:

Students measure the speed of a wave on a
string for five combinations of amplitude, frequency, tension, and wavelength. They try to
conclude what affects the speed (only tension) and the formula for the speed c = fl.

*** Lesson 5.4 – Standing Waves:

Students use a Phet simulation and ropes or phone cords
to investigate the frequencies of standing waves.
Assessment 5.2 – Standing Waves: Students are assigned wave parameters to investigate
using the Phet simulation. This is basically a repeat of Lesson 5.4 to be done individually.

*** Lesson 5.5 – Measuring the Speed of Sound:

Students work in groups to measure the
speed of sound in air. Then they all go to the athletic field. One group goes all the way
to the east end near the fence and the other group goes to the edge of the parking lot.
The first group uses the air horns to make a noise and the second group tries to measure
the time it takes the noise to get to them by listening both to the noise on their phones
and by ear. We tried doing this with the Sound Meter tool app in the Physics Toolbox
Suite but the background noise was too high, so students just used their phone
stopwatches to time the difference between the two noise pulses. The actual difference
is about 0.5 seconds, which is hard to measure accurately so most measurements were
to high, resulting in slower wave speeds than the correct value. But they enjoyed going
out and making noise so it was well worth it.

*** Lesson 5.6 – Building a Loudspeaker:

Students work in groups to build a working
loudspeaker out of a plastic cup, small disc magnets, and a copper coil (there are many
saved from the motors or they can make a new one). Then the students connect them to
a music app on a computer and listen to a song – easy and fun!

*** Lesson 5.7 – Notes on Waves:

Students take notes on waves. An important part of the
notes is introducing the electromagnetic wave spectrum (not on the paper notes). I think
more time could be spent talking about EM waves as a combination of magnetic and
electric fields, but maybe that is too advanced.

*** Lesson 5.8 – Electromagnetic Wave Characteristics:

Students research characteristics of
electromagnetic waves.

*** Assessment 5.3 – Wave Topics Research:

Students pick one of seven topics and do research
to answer questions about the topic. This assessment could use some rewording to make sure
students dig more deeply into their topic.


** Unit 6 – Energy


*** Assessment 6.1 – Defining and Changing Energy:

Students propose answers to two questions using Schoology Discussion questions (I think these will have to be remade). I showed the
answers on a screen and guided the class to these class answers:

- Energy is the motion of a mass and is called kinetic energy.
- To change the energy of the mass its motion must be changed and this requires
an unbalanced force on the mass (sum of forces not zero).
Students got two points for answering each of these. These definitions are good for thermal
energy (molecules) and the KE of larger masses, but are less intuitive for electromagnetic
radiation.


*** Lesson 6.1 – A Model for Changing the Kinetic Energy of an Object:

Students use beanbags to visualize changes in kinetic energy and to formulate what kind of force
decreases or increases the KE.


*** Lesson 6.2 – Notes on KE and W – note that there are three parts to these notes:

These notes define the change in KE as equal to the work W done by an unbalance force.
Three kinds of KE are defined and eight kinds of force interactions are discussed, some
of which are classified as potential energy changes. Note: the way I teach energy is the
result of thinking about it for a long time, but it still needs work.


*** Lesson 6.3 – Example Calculations of DKE and W:

Students use the notes to make
calculations of energy changes.


*** Assessment 6.2 – Calculating $DKE$ and W:

This assessment uses a Schoology Assessment that
replicates the equations in Lesson 6.3 but with different numbers. I am afraid that assessment
is probably not recoverable, but you could try.


*** Lesson 6.4 – Measuring Electricity:

Students work in teams to use the Kill-a-Watt meters
(in Room 302) to measure or calculate the voltage, current, and resistance of different
electrical devices in the classroom.


*** Lesson 6.5 – Energy Systems:

Students are introduced to the topic of energy systems
and use a Phet app to explore an energy system. Note: This is pretty much the same as
Chemistry lesson 3.11. Note also that if I had more time I would have had them do
Chemistry lesson 3.12.i


*** Assessment 6.3 – Energy System Project:

Students work individually to define an energy
system and to use what they have learned to answer questions about it. Note: this is essentially
the same as Chemistry Assessment 3.3.

